helmDefaults:
  recreatePods: false
  tillerless: true

releases:
  - name: discourse
    namespace: discourse
    chart: .
    values:
      - ./helmfile/base.yaml.gotmpl
      - ./helmfile/ingress.yaml.gotmpl
      - ./helmfile/postgres.yaml.gotmpl
      - ./helmfile/redis.yaml.gotmpl
    secrets: []
