apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "synapse.fullname" . }}-init
  labels:
    {{- include "synapse.labels" . | nindent 4 }}
data:
  script.sh: |-
    #!/bin/sh

    {{- if not (hasKey .Values.podSecurityContext "fsGroup") }}
    chown -v -R 991:991 /data
    {{- end }}

    /start.py generate
