apiVersion: v1
kind: Secret
metadata:
  name: {{ include "discourse.fullname" . }}-envs
  labels:
    {{- include "discourse.labels" . | nindent 4 }}
data:
  DISCOURSE_PASSWORD: "{{ .Values.admin.password | b64enc }}"
  DISCOURSE_POSTGRESQL_PASSWORD: "{{ .Values.postgresql.postgresqlPassword | b64enc }}"
  POSTGRESQL_ROOT_PASSWORD: "{{ .Values.postgresql.postgresqlPostgresPassword | b64enc }}"
  POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD: "{{ .Values.postgresql.postgresqlPassword | b64enc }}"
  {{- if .Values.redis.usePassword }}
  REDIS_PASSWORD: "{{ .Values.redis.password | b64enc }}"
  {{- end }}
