apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "riot-web.fullname" . }}
  labels:
    {{- include "riot-web.labels" . | nindent 4 }}
data:
  config.json: |-
    {{ .Values.config | toJson }}